- name: installing backend 
  hosts: backend
  become: yes 
  # vars:
  #   login_host: bend.bigmatrix.in
  #   login_password: ExpenseApp@1
  tasks:
    - name: desable node js 
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable node js 
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs 
      ansible.builtin.dnf:
        name: nodejs 
        state: present

    - name: add user 
      ansible.builtin.user:
        name: expense

    - name: creating app directory 
      ansible.builtin.file:
        path: /app 
        state: directory
    
    - name: downloading code 
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    
    - name: unzipping 
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    
    - name: npm installing 
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy backend service
      ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service


    - name: deamon reload service
      ansible.builtin.systemd_service:
       name: backend
       state: reloaded

    - name: restart backend service
      ansible.builtin.service:
       name: backend
       state: restarted

    - name: install mysql -y
      ansible.builtin.package:
       name: mysql
       state: started

    - name: loading schema
      ansible.builtin.command: mysql -h  -uroot -pExpenseApp@1 < /app/schema/backend.sql


      




      
      