- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable nodejs -y
      ansible.builtin.command: dnf module disable nodejs -y
      
    - name: enable nodejs:20 -y
      ansible.builtin.command: dnf module enable nodejs:20 -y
      

    - name: adding user
      ansible.builtin.user:
       name: expense
    
    - name: Remove /app if it's a file
      ansible.builtin.file:
        path: /app
        state: absent

    - name: creating app directory 
      ansible.builtin.file:
        path: /app 
        state: directory
        # when: not directory_exists

    - name: download the application
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        # src: /tmp/backend.zip
        dest: /app


    # - name: change directory
    #   ansible.builtin.file:
    #    dest: /app

    - name: unzip backend code
      ansible.builtin.unarchive:
       src: /tmp/backend.zip 
       dest: /app
       remote_src: yes
       


    - name: installing npm depndensies
      ansible.builtin.shell: npm install
      args:
        chdir: /app


    - name: copy backend service
      ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service


    - name: deamon reload service
      ansible.builtin.service:
       name: backendservice.repo
       state: reloaded

    - name: start backend service
      ansible.builtin.service:
       name: backend
       state: started

    - name: enable backend service
      ansible.builtin.service:
       name: backend
       enabled: yes

    - name: install mysql -y
      ansible.builtin.package:
       name: mysql
       state: started

    - name: loading schema
      ansible.builtin.command: mysql -h  -uroot -pExpenseApp@1 < /app/schema/backend.sql


      




      
      