- name: installing  mysql
  hosts: database
  become: yes
  
  tasks:
   - name: installing mysql
     ansible.builtin.package:
      name: mysql
      state: present

   
   - name: start and enable mysql servers
     ansible.builtin.service:
      name: mysqld
	•   state: started
      enabled: yes


  
   - name: mysql_secure installation
     ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
          
