- name:  installing mysql 
  hosts: backend 
  become: yes 
  tasks:
    - name: install mysql 
      ansible.builtin.command: dnf install mysql-server -y
    
    - name: start and enable mysql 
      ansible.builtin.service:
        name: mysql
           enabled: yes
           state: started
    
    - name: setup root passwor
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1

          
