- name: install mysql
  hosts: database
  become: yes
  
  tasks:
   - name: installing mysql
     ansible.builtin.package:
      name: mysql
      state: present

   - name: enabling mysql
     ansible.builtin.service:
       name: mysqld      
       enabled: yes
       state: started


  - name: starting mysql
    ansible.builtin.service:
      name: mysqld
      state: present

  - name: mysql_secure installation
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
          
