- name: install mysql
  hosts: database
  become: yes
  
  tasks:
   - name: installing mysql
     ansible.builtin.package:
      name: mysql
      state: present

  - name: enabling mysqld
    community.mysql.mysql_db:
     - name: enable mysqld
       state: present

  - name: starting mysqld
    community.mysql.mysql_db:
     - name: starting mysqld
       state: present

  - name: mysql_secure installation
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
          
