- name: installing  mysql
  hosts: database
  become: yes
  
  tasks:
   - name: installing mysql
     ansible.builtin.command: dnf module disable mysql -y
      

   - name: enabling mysql
     ansible.builtin.service:
      name: mysqld     
      state: started
      enabled: yes


   - name: starting mysql
     ansible.builtin.service:
      name: mysql
      state: started

   - name: mysql_secure installation
     ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
          
