- name:  installing mysql 
  hosts: backend 
  become: yes 
  tasks:
    - name: install mysql 
      ansible.builtin.command: dnf install mysql-server -y
    
    - name: Start and enable MySQL
      ansible.builtin.service:
        name: mysqld
        enabled: true
        state: started
    
    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1




          
