- name: configure froentend
  hosts: froentend
  become: yes
  tasks:
   - name: install nginx -y
     ansible.builtin.dnf:
      name: nginx
      state: present 

   - name: enable nginx service
     ansible.builtin.service:
      name: nginx
      enabled: yes 


   - name: daemon_ reload nginx service
     ansible.builtin.systemd_service:
      name: nginx
      state: reloaded

   - name: removing content
     ansible.builtin.file:
      path: /usr/share/nginx/html/*
      name: html
      state: absent

   - name: downloading the content
     ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

   - name: extract the content
     ansible.builtin.unarchive:
      src:  /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

   - name: unarchive the file
     ansible.builtin.unarchive:
      src: /usr/share/nginx/html
      dest: /tmp/frontend.zip
      remote_src: yes

   - name: copy content
     ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

   

   - name: reatart nginx
     ansible.builtin.service:
      name: nginx 
      status: started

      

    
