- name: installing nginx
  become: yes
  hosts: froentend
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
       name: nginx
       state: present

    - name: enabling nginx
      ansible.builtin.service:
       name: nginx
       enabled: yes
      
    - name: starting nginx
      ansible.builtin.service:
       name: nginx
       state: started
       

    - name: removing html 
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent

    - name: downloading the frontend 
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip 
        dest: /tmp


    - name: change the directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory


    - name: extract the application
      ansible.builtin.unarchive: 
       src: /tmp/expense-frontend-v2.zip  
       dest: /usr/share/nginx/html
       remote_src: yes

    - name: copying config file
      ansible.builtin.copy:
       src: expense.config
       dest: /etc/nginx/default.d/expense.config

    - name: restarting nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


