- name: configure froentend
  hosts: froentend
  become: yes
  tasks:
   - name: install nginx -y
     ansible.builtin.dnf:
      name: nginx
      state: present 

   - name: enable nginx service
     ansible.builtin.service:
      name: nginx
      enabled: yes 


   - name: daemon_ reload nginx service
     ansible.builtin.systemd_service:
      name: nginx
      state: reloaded

   - name: removing content
     ansible.builtin.file:
      path: /usr/share/nginx/html/*
      name: html
      state: absent

   - name: create html directory
     ansible.builtin.file:
      path: cd /usr/share/nginx/html
      state: directory

   - name: download and unarchive code
     ansible.builtin.unarchive:
      src:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dect: /usr/share/nginx/html

   

   - name: copy content
     ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

   

   - name: reatart nginx
     ansible.builtin.service:
      name: nginx 
      status: started

      

    
