- name:  congifure mysql server
  hosts: database
  become: yes
  tasks:
    - name: install mysql server -y
      ansible.builtin.dnf:
        name: mysql 
        state: latest
        

    - name: enabling mysql server
      ansible.builtin.service:
       name: mysql
       enabled: yes

    - name: start mysql server
      ansible.builtin.service:
      name: mysql
      status: started

    # password  
    - name: stetting password 
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1



       